# This is a basic workflow to help you get started with Actions

name: Docker Build and Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Build Angular app Docker image
        run: docker build -t damqng95/test2:test1 .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push damqng95/test2:test1
  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy with Docker Compose
        run: docker-compose up -d

      - name: Check Docker containers
        run: docker ps -a


      
      - name: Wait for Deployment
        run: sleep 10s  # Adjust the duration based on your app's startup time
     
      - name: Verification
        run: curl http://localhost:8080
      
      - name: Show Deployment URL
        run: |
          # Replace 'your-app-name' and 'your-port' with the actual values
          echo "Application deployed successfully!"
          echo "Access it at: http://${{github.server_ip}}:${{github.port}}"

    
